In [1]:
import pandas as pd

In [2]:
dd = pd.read_json("datasets/students_data.json")

In [4]:
dd.head()

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
0,1,Sabina Pandey,19,Male,9866879003,sabina.pandey1@gmail.com,Dharan,Sunsari,Koshi,"[NodeJS, C++]",17394,1532,60,84,AI Udaan Day,2026-07-26,True,False
1,2,Sujan Poudel,28,Male,9870676580,sujan.poudel2@gmail.com,Nepalgunj,Banke,Lumbini,[Flutter],46200,3006,75,78,Evening,2026-12-02,True,False
2,3,Nabin Pandey,26,Male,9834006426,nabin.pandey3@gmail.com,Kathmandu,Kathmandu,Bagmati,"[Django, Deep Learning, Python, React]",37409,3541,94,59,Weekend,2026-08-06,True,False
3,4,Roshan Regmi,27,Female,9811229824,roshan.regmi4@gmail.com,Dharan,Sunsari,Koshi,"[Figma, Python, Flutter, Excel]",47846,1196,90,73,Weekend,2026-10-20,True,False
4,5,Anisha Regmi,25,Male,9824458163,anisha.regmi5@gmail.com,Chitwan,Chitwan,Bagmati,[Data Science],23403,6333,76,62,Evening,2026-12-20,True,False

In [8]:
dd.tail(3)

,id,name,age,gender,phone,email,location,district,province,courses_enrolled,fees_paid,fees_due,attendance,marks,batch,join_date,passed,scholarship
497,498,Sabina Khadka,25,Male,9820772678,sabina.khadka498@gmail.com,Janakpur,Dhanusha,Madhesh,"[C++, Digital Marketing, Excel, Power BI]",16298,2316,81,85,Evening,2026-07-15,True,False
498,499,Rohan Acharya,30,Female,9833337211,rohan.acharya499@gmail.com,Chitwan,Chitwan,Bagmati,"[C++, Digital Marketing]",37942,1242,73,65,Evening,2026-01-09,True,False
499,500,Sujan KC,23,Female,9840665873,sujan.kc500@gmail.com,Nepalgunj,Banke,Lumbini,"[Figma, AI/ML]",27145,917,65,98,Morning,2026-12-19,True,False

In [10]:
dd.shape

(500, 18)

In [13]:
dd.dtypes

id                   int64
name                   str
age                  int64
gender                 str
phone                int64
email                  str
location               str
district               str
province               str
courses_enrolled    object
fees_paid            int64
fees_due             int64
attendance           int64
marks                int64
batch                  str
join_date              str
passed                bool
scholarship           bool
dtype: object

In [14]:
dd.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                500 non-null    int64
 1   name              500 non-null    str
 2   age               500 non-null    int64
 3   gender            500 non-null    str
 4   phone             500 non-null    int64
 5   email             500 non-null    str
 6   location          500 non-null    str
 7   district          500 non-null    str
 8   province          500 non-null    str
 9   courses_enrolled  500 non-null    object
 10  fees_paid         500 non-null    int64
 11  fees_due          500 non-null    int64
 12  attendance        500 non-null    int64
 13  marks             500 non-null    int64
 14  batch             500 non-null    str
 15  join_date         500 non-null    str
 16  passed            500 non-null    bool
 17  scholarship       500 non-null    bool
dtypes: bool(2), int64(7), object(1), str(8)
memory usage: 63.6+ KB

In [15]:
dd.describe()

,id,age,phone,fees_paid,fees_due,attendance,marks
count,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.000000,500.000000
mean,250.500000,23.746000,9.850151e+09,33232.086000,5137.020000,80.402000,71.670000
std,144.481833,3.932482,2.944077e+07,10109.900089,2947.700174,12.436951,16.250454
min,1.000000,17.000000,9.800039e+09,15148.000000,29.000000,60.000000,45.000000
25%,125.750000,20.000000,9.823999e+09,23946.000000,2458.750000,69.000000,58.000000
50%,250.500000,24.000000,9.851883e+09,34022.500000,5427.500000,81.000000,70.000000
75%,375.250000,27.000000,9.875147e+09,41986.500000,7572.250000,92.000000,86.000000
max,500.000000,30.000000,9.899911e+09,49911.000000,9986.000000,100.000000,99.000000